In [52]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [53]:
genes = pd.read_csv("data_set_ALL_AML_train.csv")

In [54]:
genes.columns

Index(['Gene Description', 'Gene Accession Number', '1', 'call', '2', 'call.1',
       '3', 'call.2', '4', 'call.3', '5', 'call.4', '6', 'call.5', '7',
       'call.6', '8', 'call.7', '9', 'call.8', '10', 'call.9', '11', 'call.10',
       '12', 'call.11', '13', 'call.12', '14', 'call.13', '15', 'call.14',
       '16', 'call.15', '17', 'call.16', '18', 'call.17', '19', 'call.18',
       '20', 'call.19', '21', 'call.20', '22', 'call.21', '23', 'call.22',
       '24', 'call.23', '25', 'call.24', '26', 'call.25', '27', 'call.26',
       '34', 'call.27', '35', 'call.28', '36', 'call.29', '37', 'call.30',
       '38', 'call.31', '28', 'call.32', '29', 'call.33', '30', 'call.34',
       '31', 'call.35', '32', 'call.36', '33', 'call.37'],
      dtype='object')

In [55]:
expression_values = [column for column in genes if "call" not in column]

creating list of columns' names only with expression values. where 'coll' word is not found
then this list of columns names is given to a DataFrame genes obj as a key, so it gets only the columns (the Series obj with expression values)

In [56]:
genes = genes[expression_values]

In [57]:
genes[:10]

,Gene Description,Gene Accession Number,1,2,3,4,5,6,7,8,...,35,36,37,38,28,29,30,31,32,33
0,AFFX-BioB-5_at (endogenous control),AFFX-BioB-5_at,-214,-139,-76,-135,-106,-138,-72,-413,...,7,-213,-25,-72,-4,15,-318,-32,-124,-135
1,AFFX-BioB-M_at (endogenous control),AFFX-BioB-M_at,-153,-73,-49,-114,-125,-85,-144,-260,...,-100,-252,-20,-139,-116,-114,-192,-49,-79,-186
2,AFFX-BioB-3_at (endogenous control),AFFX-BioB-3_at,-58,-1,-307,265,-76,215,238,7,...,-57,136,124,-1,-125,2,-95,49,-37,-70
3,AFFX-BioC-5_at (endogenous control),AFFX-BioC-5_at,88,283,309,12,168,71,55,-2,...,132,318,325,392,241,193,312,230,330,337
4,AFFX-BioC-3_at (endogenous control),AFFX-BioC-3_at,-295,-264,-376,-419,-230,-272,-399,-541,...,-377,-209,-396,-324,-191,-51,-139,-367,-188,-407
5,AFFX-BioDn-5_at (endogenous control),AFFX-BioDn-5_at,-558,-400,-650,-585,-284,-558,-551,-790,...,-478,-557,-464,-510,-411,-155,-344,-508,-423,-566
6,AFFX-BioDn-3_at (endogenous control),AFFX-BioDn-3_at,199,-330,33,158,4,67,131,-275,...,-351,40,-221,-350,-31,29,324,-349,-31,-141
7,AFFX-CreX-5_at (endogenous control),AFFX-CreX-5_at,-176,-168,-367,-253,-122,-186,-179,-463,...,-290,-243,-390,-202,-240,-105,-237,-194,-223,-315
8,AFFX-CreX-3_at (endogenous control),AFFX-CreX-3_at,252,101,206,49,70,87,126,70,...,283,119,-1,249,150,42,105,34,-82,206
9,AFFX-BioB-5_st (endogenous control),AFFX-BioB-5_st,206,74,-215,31,252,193,-20,-169,...,247,-131,358,561,24,524,167,-56,176,321

In [58]:
genes1 = genes.drop(["Gene Description", "Gene Accession Number"], axis=1)

In [59]:
genes1[:10]

,1,2,3,4,5,6,7,8,9,10,...,35,36,37,38,28,29,30,31,32,33
0,-214,-139,-76,-135,-106,-138,-72,-413,5,-88,...,7,-213,-25,-72,-4,15,-318,-32,-124,-135
1,-153,-73,-49,-114,-125,-85,-144,-260,-127,-105,...,-100,-252,-20,-139,-116,-114,-192,-49,-79,-186
2,-58,-1,-307,265,-76,215,238,7,106,42,...,-57,136,124,-1,-125,2,-95,49,-37,-70
3,88,283,309,12,168,71,55,-2,268,219,...,132,318,325,392,241,193,312,230,330,337
4,-295,-264,-376,-419,-230,-272,-399,-541,-210,-178,...,-377,-209,-396,-324,-191,-51,-139,-367,-188,-407
5,-558,-400,-650,-585,-284,-558,-551,-790,-535,-246,...,-478,-557,-464,-510,-411,-155,-344,-508,-423,-566
6,199,-330,33,158,4,67,131,-275,0,328,...,-351,40,-221,-350,-31,29,324,-349,-31,-141
7,-176,-168,-367,-253,-122,-186,-179,-463,-174,-148,...,-290,-243,-390,-202,-240,-105,-237,-194,-223,-315
8,252,101,206,49,70,87,126,70,24,177,...,283,119,-1,249,150,42,105,34,-82,206
9,206,74,-215,31,252,193,-20,-169,506,183,...,247,-131,358,561,24,524,167,-56,176,321

In [60]:
genes1 = genes1.T

In [61]:
genes1.head()

,0,1,2,3,4,5,6,7,8,9,...,7119,7120,7121,7122,7123,7124,7125,7126,7127,7128
1,-214,-153,-58,88,-295,-558,199,-176,252,206,...,185,511,-125,389,-37,793,329,36,191,-37
2,-139,-73,-1,283,-264,-400,-330,-168,101,74,...,169,837,-36,442,-17,782,295,11,76,-14
3,-76,-49,-307,309,-376,-650,33,-367,206,-215,...,315,1199,33,168,52,1138,777,41,228,-41
4,-135,-114,265,12,-419,-585,158,-253,49,31,...,240,835,218,174,-110,627,170,-50,126,-91
5,-106,-125,-76,168,-230,-284,4,-122,70,252,...,156,649,57,504,-26,250,314,14,56,-25

In [62]:
from sklearn.decomposition import FactorAnalysis
from sklearn import preprocessing

In [64]:
genes_normal = preprocessing.scale(genes1)
type(genes1)

pandas.core.frame.DataFrame

In [65]:
factor = FactorAnalysis(n_components=5).fit(genes_normal)

In [66]:
factor_arr = pd.DataFrame(factor.components_, columns=genes1.columns)

In [67]:
factor_arr

,0,1,2,3,4,5,6,7,8,9,...,7119,7120,7121,7122,7123,7124,7125,7126,7127,7128
0,-0.432613,-0.231327,0.057284,0.328930,-0.610826,-0.644121,0.113295,-0.593452,0.189487,0.156140,...,0.407302,0.493299,-0.076735,-0.224698,0.099082,0.769069,0.694201,0.310245,0.078972,-0.033392
1,0.021651,-0.108063,-0.082077,0.137228,0.247428,0.384464,0.178814,0.405026,-0.307845,0.169095,...,0.206490,0.153642,-0.036021,0.013712,0.050882,-0.129810,0.061853,0.405610,-0.261742,-0.144204
2,0.132899,0.157208,0.052644,0.624423,0.363276,0.329098,-0.020927,-0.035877,-0.144983,0.314901,...,0.090011,0.105594,0.065805,0.107025,0.025256,0.282404,-0.263007,-0.139691,0.397341,0.159616
3,-0.496418,-0.195974,-0.042762,-0.036326,0.021761,0.316818,0.025302,0.270403,0.009044,-0.081449,...,-0.151123,-0.048980,0.324344,0.091586,0.189897,-0.125574,0.298811,-0.161974,-0.047665,-0.202905
4,0.006367,0.255835,0.030821,0.132943,0.316255,0.028314,0.084173,0.123657,-0.165447,-0.088259,...,0.201795,0.358282,0.258490,-0.151509,0.138692,-0.354826,0.099381,0.220773,-0.342472,-0.170935

In [68]:
from sklearn.decomposition import PCA

In [69]:
pca = PCA(n_components=20).fit(genes_normal)

In [70]:
pca

PCA(copy=True, iterated_power='auto', n_components=20, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [72]:
pca.explained_variance_ratio_

array([ 0.14987793,  0.11977811,  0.06600567,  0.04884914,  0.04632394,
        0.03721899,  0.03490611,  0.03289449,  0.02985107,  0.02644982,
        0.02508908,  0.02356967,  0.02204286,  0.020833  ,  0.0193352 ,
        0.01887967,  0.0183928 ,  0.01708522,  0.01698242,  0.01610236])